//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infi.LuceneArticle.LuceneUpdateQueue.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("luceneupdatequeue")]
        public string AzureStorageQueueName {
            get {
                return ((string)(this["AzureStorageQueueName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<FILL ME, OR UPDATE .CONFIG FROM RUNNING PROJECT>")]
        public string AzureStorageQueueConnectionString {
            get {
                return ((string)(this["AzureStorageQueueConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("luceneupdatequeue")]
        public string AzureServiceBusQueueName {
            get {
                return ((string)(this["AzureServiceBusQueueName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<FILL ME, OR UPDATE .CONFIG FROM RUNNING PROJECT>")]
        public string AzureServiceBusQueueConnectionString {
            get {
                return ((string)(this["AzureServiceBusQueueConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<FILL ME, OR UPDATE .CONFIG FROM RUNNING PROJECT>")]
        public string AzureObjectStoreBlobConnectionString {
            get {
                return ((string)(this["AzureObjectStoreBlobConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("blobs")]
        public string AzureObjectStoreBlobContainer {
            get {
                return ((string)(this["AzureObjectStoreBlobContainer"]));
            }
        }
    }
}
